# Generated by Django 4.0.1 on 2023-01-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bookmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmode',
            name='about',
            field=models.ManyToManyField(blank=True, to='users.ProfileModel'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_link',
            field=models.ManyToManyField(blank=True, to='users.LinkModel'),
        ),
    ]
