# Generated by Django 4.1 on 2022-09-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_chapter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
