# Generated by Django 4.0.1 on 2023-01-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_bookmode_about_alter_profilemodel_profile_link'),
        ('stories', '0011_delete_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='about',
            field=models.ManyToManyField(blank=True, to='users.ProfileModel'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='stories.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='chapters',
            field=models.ManyToManyField(blank=True, to='stories.Story'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='stories.Tag'),
        ),
    ]
