# Generated by Django 4.0.7 on 2023-02-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0015_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
