# Generated by Django 4.0.7 on 2023-02-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0019_post_dislikes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title_link',
        ),
    ]
