# Generated by Django 4.0.7 on 2023-02-07 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0022_remove_comment_title_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stories.title'),
            preserve_default=False,
        ),
    ]
