# Generated by Django 4.0.7 on 2023-02-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0024_remove_comment_title_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
