# Generated by Django 4.1 on 2022-08-29 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_remove_story_book_story_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='book',
        ),
        migrations.AddField(
            model_name='story',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stories.book'),
            preserve_default=False,
        ),
    ]
