# Generated by Django 4.1 on 2022-09-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='chapters',
            field=models.ManyToManyField(blank=True, to='stories.story'),
        ),
    ]
