# Generated by Django 4.0.7 on 2023-01-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_namemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('hint', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
