# Generated by Django 4.1.5 on 2023-02-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_namemodel_namesmodel_alter_quizmodel_question_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NameModel',
        ),
    ]
