# Generated by Django 4.0.7 on 2023-01-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_quizmodel_question_lognames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lognames',
            name='user',
        ),
    ]
