# Generated by Django 4.0.7 on 2023-01-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_lognames_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lognames',
            name='game',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
