# Generated by Django 4.0.7 on 2023-01-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_logname_lognumber_delete_lognames'),
    ]

    operations = [
        migrations.AddField(
            model_name='logname',
            name='games',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='logNumber',
        ),
    ]
