# Generated by Django 4.0.7 on 2023-01-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_logname_games_delete_lognumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='logname',
            name='gp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
